# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Local Config
# To serve the local site, run:
# jekyll serve --config _config.yml,_config-local.yml

# Site settings
title: 162 Unlimited
email: chris@162unlimited.com
slogan: Web Design & Development

twitter_username: ChrisAlbrecht
github_username:  keyboardcowboy

# URLs
url: "http://162unlimited.com"
baseurl: "/"
permalink: pretty

# Build settings
markdown: kramdown

# Files
exclude: ['Gemfile', 'Gemfile.lock', 'package.json', 'Gruntfile.js', 'node_modules']
